### ISSUE TITLE
Ugly GUI

### ISSUE THREAD

**Issue by AbhigyanKumar** [GiordanoSconti/nodeDestreamerGUI#1]
The **UI/UX** is pretty **ugly**. _Can I help you to make it look cool_? The only problem is I'm a web developer and it will take time to understand your project. So, can you explain how tohe program actually works behind the hood?

**Comment by GiordanoSconti** [comment]
Hi Abhigyan Kumar,
You're absolutely right about the **UI/UX, it's not neither easly readable nor easly usable and it must be made better.** I should have done a better job with that aspect of the project, but I haven't had much time to dedicate on it on the last months.

> Can I help you to make it look cool? 

**You're free to work on this project as long as you want.** 

In simple words, **Electron** environment works like a **IPC subsystem**. You have two processes that are able to exchange messages each other by using low level structures and channels (such as pipe, streams, sockets and so forth). The main process is called _"main"_ and is the nearest one to the **Chromium and Nodejs** environments (you can even disable the latter one if you don't have to use OS services). The secondary process is called _"renderer"_ and it is a kind of _"Chromium Sandbox"_ capable of talking with the main process trough IPC mechanisms. The latter one is there to do the rendering of a web page and isolate this one from the **Chromium** environment (**not the Nodejs one though**). The only way to interact with **Chromium APIs** is from the _main_ process. **That's where the IPC system comes into play**. Now, let's talk about this project:
I kept the infrastructure and the nomenclature of the **Electron subsystem**, so the main process is called _"main.js"_ and the secondary process is called _"renderer.js"_ (you can assign whatever names you want at these ones). **The _"index.html"_ file is the structure of the UI, while the _"main.css"_ file is the graphics of the UI**. Inside the _"main.js"_ script you can observe the typical behaviour of a UI Toolkit (exposed by Electron). All the methods you can see in the source code belong to the **Electron APIs and the Nodejs modules**, which call the **native APIs of the OS the application is running on**.
The regions of code of the _"main.js"_ script you're interested on are the below ones:
- **runWindow function**:
It allows you to create a new instance of BrowserWindow (Chromium browser instance), a toolbar (Menu with MenuItem objects) and a context menu with the classic voices (Cut, Paste, Copy etc...).
- **ipcMain.on event handlers**:
This is where the IPC mechanism is used. As you can notice you can customize the names of the events and the Message structure that I chose to use is a simple JSON object. These event handlers react on receiving messages sent by the _"renderer"_ process.
- **spawnDestreamerInfo and ipcMain.on("commandExecuted")**:
They occupy to spawn a new child process (a new Nodejs process that executes the destreamer.js script) and listen for real time messages from it.
- **browserWindow.webContents.send and event.reply**:
You can use these methods to send messages to the _"renderer"_ process from the _"main"_ process.

**The _"renderer"_ process uses a normal Javascript script, but you can even make use of the Nodejs modules inside of it.**. Indeed, the only way to include the **jQuery** library (and other frameworks such as **Vue**) inside the _"renderer.js"_ script is by using the Nodejs modules.
In order to communicate with the _"main"_ process, you need to use the Electron modules like _"ipcRenderer"_ (**it behaves in the same way as "ipcMain" module, but in the reverse direction: It listens for messages sent by the _"main"_ process**) and _"remote"_ (even if they are in willing to change some things in the 10th version, still in development phase). I hope I helped you somehow, if you need more info about the project infrastructure I am here to answer your questions. This week I can't work on it, but if you want to make the UI better you can start even now. I'm going to make you a collaborator of the project.

P.S.: _"utils"_ directory contains a json file which stores main tokens, while _"preferences"_ directory contains a json file which stores UI settings (you can change the names of the proprieties if you feel the need to do it, I didn't have time to pick up better names). 
I apologize with you for technical details and possible grammar typos.

**Comment by AbhigyanKumar** [comment]
Thanks @GiordanoSconti. Yep! This explained everythin required. Now, I would enhance the GUI appearence. I will try to use least number of libraries such as Bootstrap or Foundation and use plain HTML, CSS and JS instead.
